spring.application.name=site_pl_99

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_URL:172.17.0.2}:${DB_PORT:5432}/${DB_NAME:site_pl_99}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS:postgres_pl_99}

#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.sql=debug


spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

password.strengh = 4
