

###
GET http://localhost:8080/api/auth/current
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6W3sidGl0bGUiOiJBRE1JTiJ9LHsidGl0bGUiOiJVU0VSIn0seyJ0aXRsZSI6IkdVRVNUIn0seyJ0aXRsZSI6Ik1BTkFHRVIifV0sImlkIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDg0NDI3NjcsImV4cCI6MTc0ODQ0MzEyN30.qUqRMLVcScXuMCBox16PMW4ESyLYhdGrrdgExhBGOIovPgHaVLmi7A9nToghae8A






###
POST http://localhost:8080/api/auth/login?
    username=admin&
    password=admin