

###
GET http://localhost:8080/api/auth/current
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6W3sidGl0bGUiOiJBRE1JTiJ9LHsidGl0bGUiOiJVU0VSIn0seyJ0aXRsZSI6IkdVRVNUIn0seyJ0aXRsZSI6Ik1BTkFHRVIifV0sImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDkyNzM1OTMsImV4cCI6MTc0OTI3Mzk1M30.AAnnYYrwR4SLwzMO1pJ6wq2i6cDg9yeJv5YNS_hp32tuzsa7-lj6-Luwlslr9ruO







###
POST http://localhost:8080/api/auth/login?
    username=admin&
    password=admin