

################### Запроссы на Открытый энд поинт для всех ######################
###
GET http://localhost:8080/api/test/open-all

###
GET http://localhost:8080/api/test/open-all
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6W3sidGl0bGUiOiJBRE1JTiJ9LHsidGl0bGUiOiJVU0VSIn0seyJ0aXRsZSI6IkdVRVNUIn0seyJ0aXRsZSI6Ik1BTkFHRVIifV0sImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDgyNDY4MDAsImV4cCI6MTc0ODI0NzE2MH0.pDkdDriD1obXYfm8HRvmhlRsD6uZ8xmCTvVthW1C8QA1em8GQBtbWf5Sgf9HnR-o
###************************************************************************************###




#######################  Запросы для всех авторезированных пользователей ##############
###
GET http://localhost:8080/api/test/open-auth
#Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6W3sidGl0bGUiOiJBRE1JTiJ9LHsidGl0bGUiOiJVU0VSIn0seyJ0aXRsZSI6IkdVRVNUIn0seyJ0aXRsZSI6Ik1BTkFHRVIifV0sImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDgyNDcyMjYsImV4cCI6MTc0ODI0NzU4Nn0.R6drIj1zwsSGD1gCw_RuCq4LRee6AXYQPQU_aXoi033lBEbUFHBfl5YEaxzlkCE-

###
GET http://localhost:8080/api/test/open-auth
Authorization: Basic guest guest

###
GET http://localhost:8080/api/test/open-auth
Authorization: Basic user user

###
GET http://localhost:8080/api/test/open-auth
Authorization: Basic user-guest user-guest

###
GET http://localhost:8080/api/test/open-auth
Authorization: Basic admin-guest admin-guest

###
GET http://localhost:8080/api/test/open-auth
Authorization: Basic admin-user admin-user
###************************************************************************************###



#####################  Доступ только Админу ##############################################
GET http://localhost:8080/api/test/open-admin
Authorization: Basic admin admin
###************************************************************************************###



#####################  Доступ только Гостю ###############################################
GET http://localhost:8080/api/test/open-guest
Authorization: Basic guest guest
###************************************************************************************###



#####################  Доступ только Пользователю ########################################
GET http://localhost:8080/api/test/open-user
Authorization: Basic user user
###************************************************************************************###




#####################  Доступ только Админу и Гостю ######################################
GET http://localhost:8080/api/test/open-admin-guest
Authorization: Basic admin-guest admin-guest
###************************************************************************************###



#####################  Доступ только Админу и Пользователю ###############################
GET http://localhost:8080/api/test/open-admin-user
Authorization: Basic admin-user admin-user
###************************************************************************************###



#####################  Доступ только гостю и Пользователю ################################
GET http://localhost:8080/api/test/open-guest-user
Authorization: Basic user-guest user-guest
###************************************************************************************###